apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  selector:
    app: dex
  ports:
    - name: http
      port: 5556
      targetPort: 5556
    - name: telemetry
      port: 5558
      targetPort: 5558
