-- Site assets: uploaded files served from the owner host, outside every
-- vN/ so they survive deploys and rollbacks (design.md 7.3).
--
-- This table is metadata only. The bytes live on disk at
-- <SITE_DIR>/<owner>/<site>/assets/<id> (internal/storage), written and
-- deleted by the storage layer; this row is what a listing, an audit trail,
-- and the per-site quota query read without touching the filesystem. id is
-- generated by the storage layer (not by this table's default) so the
-- database row and the on-disk filename always agree — it is still typed
-- uuid, and DEFAULT gen_random_uuid() is kept as a fallback for any future
-- caller that does not already have one.
--
-- sha256 is not part of design 7.3's table sketch; it is added here so a
-- restored asset (Phase 5's `simple-host restore`) can be verified against
-- the row that described it, the same integrity check version uploads get
-- implicitly from the archive's own extraction validation.
--
-- Numbered 0026, not design 7.3's illustrative 0024: Phase 2 owns both 0024
-- (site_viewers) and 0025, and Phase 4's audit_events takes 0027 (see
-- 0020_app_role_grants.sql's comment on merge-order numbering).

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS site_assets (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    site_id      uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    name         text NOT NULL,
    content_type text NOT NULL,
    size         bigint NOT NULL CHECK (size >= 0),
    sha256       bytea NOT NULL,
    created_by   uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    deleted_at   timestamptz
);

-- The listing and quota-sum queries (design 7.3: per-site count and byte
-- limits) both filter "this site, not deleted, newest first" — a partial
-- index keeps a soft-deleted asset's row out of the index entirely once it
-- no longer counts against anything.
CREATE INDEX IF NOT EXISTS site_assets_site_idx ON site_assets (site_id, created_at DESC)
    WHERE deleted_at IS NULL;

-- No DELETE grant: an asset row is soft-deleted (an UPDATE of deleted_at),
-- the same narrow-privilege reasoning 0020's comment gives audit_events.
-- The row is only ever hard-removed by sites' ON DELETE CASCADE, which runs
-- under the schema-owning role during a site's own deletion, not under
-- simplehost_app.
GRANT SELECT, INSERT, UPDATE ON TABLE site_assets TO simplehost_app;

COMMIT;
